# Generated by Django 3.0.4 on 2020-03-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftsdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airportsdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='boardingpasses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketflights',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={},
        ),
    ]
